### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by ruihash** [ruihash/protospace-40182#1]
#URL
https://protospace-40182.onrender.com/

**Comment by yusuketono** [comment]
@ruihash さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
#### プロトタイプ編集機能
- [x] **正しく編集できた場合は、詳細ページへ遷移すること**
トップページに遷移してしまうので、詳細ページに遷移するようにしましょう。

#### その他
- [x] **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされること**
他のユーザーのプロトタイプ編集ページに遷移できてしまうので、修正しましょう。
```
【チェック方法】
先ず、ユーザーAで投稿したプロトタイプの編集ページURLをコピー。
次に、ユーザーBでログインし、そのURLを直接入力した際に、トップページへリダイレクトされれば正常な挙動。
```
修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/GHoamSpyb7Yvmjx47

**Comment by ruihash** [comment]
修正完了しました

**Comment by ruihash** [comment]
ありがとうございました
